# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/canberk/UnrealEngine5.5

TARGETS = \
	GameGineCase-Android-DebugGame  \
	GameGineCase-Android-Development  \
	GameGineCase-Android-Shipping  \
	GameGineCase-Linux-DebugGame  \
	GameGineCase-Linux-Development  \
	GameGineCase-Linux-Shipping  \
	GameGineCase-LinuxArm64-DebugGame  \
	GameGineCase-LinuxArm64-Development  \
	GameGineCase-LinuxArm64-Shipping  \
	GameGineCase \
	GameGineCaseEditor-Linux-DebugGame  \
	GameGineCaseEditor-Linux-Development  \
	GameGineCaseEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend GameGineCaseEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug GameGineCaseEditor-Linux-Debug


GameGineCase-Android-DebugGame:
	 $(BUILD) GameGineCase Android DebugGame  -Project="/home/canberk/Desktop/Projects/StealthDemo/StealthDemo.uproject" $(ARGS)

GameGineCase-Android-Development:
	 $(BUILD) GameGineCase Android Development  -Project="/home/canberk/Desktop/Projects/StealthDemo/StealthDemo.uproject" $(ARGS)

GameGineCase-Android-Shipping:
	 $(BUILD) GameGineCase Android Shipping  -Project="/home/canberk/Desktop/Projects/StealthDemo/StealthDemo.uproject" $(ARGS)

GameGineCase-Linux-DebugGame:
	 $(BUILD) GameGineCase Linux DebugGame  -Project="/home/canberk/Desktop/Projects/StealthDemo/StealthDemo.uproject" $(ARGS)

GameGineCase-Linux-Development:
	 $(BUILD) GameGineCase Linux Development  -Project="/home/canberk/Desktop/Projects/StealthDemo/StealthDemo.uproject" $(ARGS)

GameGineCase-Linux-Shipping:
	 $(BUILD) GameGineCase Linux Shipping  -Project="/home/canberk/Desktop/Projects/StealthDemo/StealthDemo.uproject" $(ARGS)

GameGineCase-LinuxArm64-DebugGame:
	 $(BUILD) GameGineCase LinuxArm64 DebugGame  -Project="/home/canberk/Desktop/Projects/StealthDemo/StealthDemo.uproject" $(ARGS)

GameGineCase-LinuxArm64-Development:
	 $(BUILD) GameGineCase LinuxArm64 Development  -Project="/home/canberk/Desktop/Projects/StealthDemo/StealthDemo.uproject" $(ARGS)

GameGineCase-LinuxArm64-Shipping:
	 $(BUILD) GameGineCase LinuxArm64 Shipping  -Project="/home/canberk/Desktop/Projects/StealthDemo/StealthDemo.uproject" $(ARGS)

GameGineCase: GameGineCase-Linux-Development

GameGineCaseEditor-Linux-DebugGame:
	 $(BUILD) GameGineCaseEditor Linux DebugGame  -Project="/home/canberk/Desktop/Projects/StealthDemo/StealthDemo.uproject" $(ARGS)

GameGineCaseEditor-Linux-Development:
	 $(BUILD) GameGineCaseEditor Linux Development  -Project="/home/canberk/Desktop/Projects/StealthDemo/StealthDemo.uproject" $(ARGS)

GameGineCaseEditor: GameGineCaseEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/canberk/Desktop/Projects/StealthDemo/StealthDemo.uproject" -Game 

.PHONY: $(TARGETS)
